aws-amplify/maplibre-gl-js-amplify

.circleci/config.yml

chore: add circleci step for build and test

---

package.json
rollup.config.js
tsconfig.json
yarn.lock

- Added rollup and terser and updated build step to generated UMD bundles

Added UMD Bundle

---

package.json

chore: 1.0.2 release

---

package.json

release 1.0.3

---

package.json

chore: v1.0.4 release

---

src/AmplifyMapLibreRequest.ts
yarn.lock

We've updated `@aws-amplify/geo` to add `region` into the `MapStyle` object so that now we can infer this for customers in `createMapLibreMap`.
Published to a local Verdaccio and testing in an example app

feat: add region integration  to `createMapLibreMap`

---

package.json

- Added prepublish command to ensure a build is made before publishing

chore: added prepublish step to build

---

package.json

chore: release v1.0.5

---

README.md
src/AmplifyMapLibreRequest.ts
src/index.ts

- Moved `createMapLibreMap` out of `AmplifyMapLibreRequest`
- Renamed to `createMap`

chore: move/refactor createMapLibreMap to createMap

---

package.json

chore: v1.0.6 prep

---

src/AmplifyMapLibreGeocoder.ts

- Remove maplibre-gl-geocoder css import

fix: remove maplibre-gl-geocoder css import

---

.github/workflows/publish.yml

- Github action / workflow created that will publish package to npm when a tagged version that starts with `v` is released

chore: add npm publish workflow

---

package.json
rollup.config.js

- Added sourceMap generation with rollup
- Minify sourceMap with terser

chore: generated sourceMap and minify it

---

API.md
CHANGELOG.md
package.json

chore: release v1.1.0, update API.md

---

API.md
__tests__/AmplifyMapLibreRequest.test.ts
src/constants.ts
src/drawClusterLayer.ts
src/drawPoints.ts

- Fix name
- https://github.com/aws-amplify/amplify-js/issues/8836

fix: rename references to Amazon Location Services to Amazon Location Service

---

package.json
yarn.lock

- Remove `start-server-and-test` and `wait-on` dependencies as they are not being used currently
- `wait-on` package was causing a security vulnerability

chore: remove unneeded dependencies to fix security vulnerability

---

src/drawUnclusteredLayer.ts

- When mousing over the point layer updates the mouse pointer style
- When leaving the point layer resets the mouse pointer style

chore: update mouse pointer when mousing over marker layer

---

package.json
src/drawPoints.ts
yarn.lock

- In some cases an unclustered marker would appear withint a clustered circle instead of becoming clustered
- Fixed the clusterRadius default to match the smallest cluster size
- Also threw in an update to package.json to use regular version instead of `geo` tag for dependencies

Fix cluster distances

---

API.md

chore: Add createMap and drawGeofences to API.md

---

API.md
src/drawPoints.ts

- Added show, hide, setData utility functions
- setData can be used to update the data poitns drawn on the map

feat: add setData, show, hide, utility functions to drawPoints return

---

CHANGELOG.md
package.json

chore: prep v1.1.3

---

package.json
src/AmplifyGeofenceControl.ts
src/geofenceUtils.ts
src/utils.ts
yarn.lock

- Added feature for creating a geofence
- Clicking add button shows a prompt for naming the geofence/ setting the id
- Clicking add confirm button adds a predefined square geofence that to the screen which the developer can edit
- Gif below of the features added

feat: Added feature for creating a new geofence with a pre-defined square

---

src/AmplifyGeofenceControl.ts

- Added ability to update geofences
- ![zxcvzxcv](https://user-images.githubusercontent.com/68032955/141953056-789cf027-195b-4318-80bd-6b71eab2e8ab.gif)

Implement update geofence

---

src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts

Implement delete geofence

---

__tests__/AmplifyGeofenceControl.test.ts
babel.config.js
jest.config.js
package.json
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
yarn.lock

- Added unit tests for save and delete
- Refactored some UI portions that were still in the control portion to the ui file
- Updated jest configuration to manually target mapbox-gl-draw for transpilation

Geofence control unit tests

---

__tests__/geofenceUtils.test.ts
package.json
src/AmplifyGeofenceControl/AmplifyMapboxDraw.ts
src/geofenceUtils.ts
src/types.ts
src/utils.ts
yarn.lock

- Added unit tests for geofenceUtils
- Refactored polygon util methods
- Updated types to match geo js
-

chore: add geofenceUtil unit tests, update types, small refactoring

---

__tests__/AmplifyGeofenceControl.test.ts
package.json
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/geofenceUtils.ts
src/public/amplify-ctrl-geofence.css
src/types.ts
src/utils.ts
yarn.lock

- Integrated with Amplify Geo Geofence CRUD APIs
- Added unit tests
- WARNING: https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/78 should be merged before this

chore: Integration with real geo apis, added tests

---

src/AmplifyGeofenceControl/AmplifyMapboxDraw.ts
src/AmplifyGeofenceControl/index.ts

- A DIY approach to fixing the bug on mapbox-draw which prevents delete keys from working on maplibre - https://github.com/mapbox/mapbox-gl-draw/pull/1079
- [] Relevant documentation is changed or added (and PR referenced)

Geofence control fix delete

---

__tests__/geofenceUtils.test.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/geofenceUtils.ts
src/public/amplify-ctrl-geofence.css

- Fix options in constructor not being optional
- Fix polygon being draw in clockwise order, should have been coutner clockwise
- Fix other small issues with UI for the list

fix: fix minor ui issues, change polygon to be drawn in counter clockwise order

---

CHANGELOG.md

chore: prep v1.2.0 launch

---

package.json

chore: prep v1.2.0 launch package.json

---

.github/workflows/publish.yml
package.json

chore: update publish workflow to include tagged geo release workflow

---

.github/workflows/publish.yml

fix: change workflow conditional to use single quotes

---

.github/workflows/publish.yml

fix: change publish workflow if statement

---

package.json

fix: move debounce to regular dependency

---

package.json

chore: update geo branch to v1.2.4-geo

---

package.json

- Fixed peer dependency versions of amplify to use `geo` tag
- Update tagged version to `v1.2.6-geo`

fix: Geo peer deps

---

src/public/amplify-map.css

- added `amplify-map.css` file
- includes `fixedheight-map`, `fullscreen-map`, `fullheight-map`

chore: add amplify-map.css file with various css configurations

---

package.json

prep v1.2.2 release

---

API.md
__tests__/geofenceUtils.test.ts
yarn.lock

- Added geofence control docs to API.md
- Added unit tests for geofenceUtils

Geo control docs

---

.circleci/config.yml

fix: update circleci workflow to use main branch

---

API.md

chore: fix geofence api.md link

---

package.json

chore: prep v1.2.3

---

.circleci/config.yml
.github/workflows/publish.yml
API.md
__tests__/drawPoints.test.ts
package.json
src/drawPoints.ts
src/public/amplify-map.css

v1.2.3 release

---

__tests__/AmplifyMapLibreGeocoder.test.ts
package.json
src/AmplifyMapLibreGeocoder.ts
src/AmplifyMapLibreRequest.ts
yarn.lock

- Add auto suggest API to AmplifyGeocoder

feat: Add stubs for auto suggest api

---

src/AmplifyMapLibreGeocoder.ts

- Fixes the autocomplete flag logic

fix: update autocomplete logic

---

API.md

chore: update amplify geocoder API docs

---

CHANGELOG.md
package.json

chore: prep v1.2.4

---

.github/workflows/publish.yml

chore: update node publish workflow version

---

src/AmplifyMapLibreGeocoder.ts

Temporarily disable autocomplete until Amplify CLI is updated to create proper permissions.
- Through a demo app

fix: temporarily disable autocomplete by default

---

CHANGELOG.md
package.json

chore: prep v1.3.1

---

package.json

fix: remove regular dependency on maplibre-gl-geocoder

---

package.json
src/AmplifyGeofenceControl/AmplifyMapDraw.ts
yarn.lock

- Depends on https://github.com/thaddmt/maplibre-gl-draw-circle/pull/1 being published

chore: change to use maplibre-gl-draw-circle

---

API.md
README.md
__tests__/drawPoints.test.ts
src/drawUnclusteredLayer.ts
src/types.ts
yarn.lock

- Added options in drawPoints for `markerImageElement` and `activeMarkerImageElement` so customers can pass their own custom icons in
- Added examples, updated docs
- Added unit tests
```
import myIcon from "./spiderman.svg"
...
const icon = new Image(100, 100);
icon.src = myIcon;
map.on("load", function () {
const output = drawPoints(
'mySourceName',
[
{
coordinates: [-122.483696, 37.833818],
title: 'Golden Gate Bridge',
address: 'A suspension bridge spanning the Golden Gate',
},
{
coordinates: [-122.477, 37.8105],
},
],
map,
{
unclusteredOptions: {
markerImageElement: icon,
activeMarkerImageElement: icon
}
}
);
```

feat: allow for customizing markers with drawPoints

---

.github/workflows/coverage.yml
codecov.yml
package.json

chore: add codecov

---

src/AmplifyGeofenceControl/ui.ts
src/public/amplify-ctrl-geofence.css

- Fixed small style issues with geofence crud, screenshots below
Info button misaligned
Create modal cut off
Create modal fixed
Info i realigned

chore: fix style for info button and create modal

---

.circleci/config.yml
.github/workflows/coverage.yml
.github/workflows/publish.yml
.husky/commit-msg
API.md
CHANGELOG.md
README.md
__tests__/AmplifyMapLibreGeocoder.test.ts
__tests__/drawPoints.test.ts
codecov.yml
commitlint.config.js
package.json
src/AmplifyMapLibreGeocoder.ts
src/AmplifyMapLibreRequest.ts
src/drawPoints.ts
src/drawUnclusteredLayer.ts
src/public/amplify-map.css
src/types.ts
yarn.lock

Merge main into Geo

---

__tests__/AmplifyGeofenceControl.test.ts
src/AmplifyGeofenceControl/icons.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/public/amplify-ctrl-geofence.css
yarn.lock

- Update geofence count not being updated on create/delete
- Update styling of delete success info box

Geofences various ux fixes

---

__tests__/AmplifyGeofenceControl.test.ts
src/AmplifyGeofenceControl/index.ts

- Fixed error messages
- removed bearing controls from navigation controls

chore: fix error messaging syntax, remove bearing from nav control

---

.circleci/config.yml
.github/workflows/coverage.yml
.github/workflows/publish.yml
.husky/commit-msg
API.md
README.md
__tests__/AmplifyMapLibreGeocoder.test.ts
__tests__/drawPoints.test.ts
codecov.yml
commitlint.config.js
package.json
src/AmplifyMapLibreGeocoder.ts
src/drawPoints.ts
src/drawUnclusteredLayer.ts
src/types.ts
yarn.lock

- Fixes issues in https://github.com/aws-amplify/maplibre-gl-js-amplify/issues/128 by creating a release to latest

chore: create release

---

__tests__/AmplifyMapLibreGeocoder.test.ts
package.json
src/AmplifyMapLibreGeocoder.ts
yarn.lock

- remove versions using geo tags
- remove getSuggestions API

fix: fix geo tagged versions for geofence crud components

---

package.json
rollup.config.js
tsconfig.json
yarn.lock

- Source maps referencing ts files that are not included in the bundle were causing warnings, removed source maps

fix: remove source maps

---

src/AmplifyGeofenceControl/AmplifyMapDraw.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/geofenceUtils.ts

- Change radius field to reflect circle mode's current radius

fix: Fix radius field to reflect circle mode radius size

---

src/AmplifyGeofenceControl/AmplifyMapDraw.ts
src/AmplifyGeofenceControl/index.ts

- Passing in the wrong argument was making the circle mode show the incorrect create options

fix: fix circle mode showing incorrect create options

---

.circleci/config.yml

- Added CRA5, TS, vue, next integ tests

chore: add cra5, ts integ tests; run integ tests on prs as well

---

.circleci/config.yml

chore: run integ tests on release branch

---

CONTRIBUTING.md

Update the name of the `main` branch in the contributing guide.
N/A
N/A

chore: Rename to main branch in contributing guide

---

__tests__/createMap.test.dom.ts
jest.config.js
jest.setup.dom.ts
package.json
yarn.lock

Adds unit testing for the `createMap` function, along with appropriate Jest configuration to test the webgl canvas output of `createMap`.
N/A
Running `yarn test` to ensure all unit tests pass/

test: Add unit test for createMap

---

package.json
yarn.lock

- Fix dependabot security alerts for amplify-ui https://github.com/aws-amplify/amplify-ui/security/dependabot

fix: pin minimist and underscore to fix security updates

---

package.json
yarn.lock

- Update to maplibre-gl-draw-circle@0.1.1 which upgrades mapbox-gl-draw version to 1.3.1
- Remove resolutions, overrides, and npm empty package
- Tested with next, CRA4, and CRA5

chore: update maplibre-gl-draw-circle@0.1.1

---

package.json
yarn.lock

- Tested changes locally with verdaccio

fix: update geocoder to v1.4.1

---

package.json
yarn.lock

fix: update maplibre-gl-geocoder to v1.4.2

---

.github/CODEOWNERS
__tests__/AmplifyMapLibreGeocoder.test.ts
package.json
src/AmplifyMapLibreGeocoder.ts
yarn.lock

Add PlaceId support for Autosuggest with APIs - getSuggestions and searchByPlaceId.
Docs PR: https://github.com/aws-amplify/docs/pull/4615

feat: add PlaceId support for Autosuggest

---

__tests__/AmplifyMapLibreRequest.test.ts
__tests__/createMap.test.dom.ts
src/AmplifyMapLibreRequest.ts

fix: update redentials to be grabbed from Credentials instead of Auth(#177)

---

README.md
package.json

fix: update peer deps to test amplify-js v5 support

---

package.json

fix: update peerDeps to point to aws-amplify 4 or 5

---

package.json

fix: update geo peerdep

---

.circleci/config.yml

fix: update integ tests to point to new branch

---

.circleci/config.yml

chore: run tests on main branch

---

__tests__/AmplifyMapLibreGeocoder.test.ts
src/popupRender.ts

Fix code scanning errors: missing semicolon and incomplete unit test
https://github.com/aws-amplify/maplibre-gl-js-amplify/security/code-scanning/2
https://github.com/aws-amplify/maplibre-gl-js-amplify/security/code-scanning/3
- [x ] PR description included
- [x ] `yarn test` passes
- [x ] Tests are [changed or added]

chore: fix code scanning errors: missing semicolon and incomplete unit test

---

src/AmplifyMapLibreRequest.ts

Amplify currently offers `getAmplifyUserAgent()` which returns a string today. It is more correct that this would return a list of `UserAgent` objects which can be translated into a string, then providing a specific string version of the method.
This function is used internally to provide the custom user agent as part of gathering usage metrics. Since the return type will change for this method, I am proposing we make this maplibre usage work with both return types today, then use the string version of the function once the change is released.
I have tested this with the new and old implementation to confirm that both work.

feat: Add support for getAmplifyUserAgent return of string or object

---

package.json
yarn.lock

- bump `@babel/preset-env`
- add `optionator` resolution
Ran unit tests locally, integ tests via CircleCi

chore: addtional updates for dependabot alerts

---

.github/CODEOWNERS

This PR updates the CodeOwners to Amplify UI team

Update CODEOWNERS to Amplify UI team

---

.github/actions/setup-samples-staging/action.yml
.github/workflows/publish.yml
package.json
src/AmplifyMapLibreRequest.ts
yarn.lock

BREAKING CHANGE: updated package to be compatible with aws-amplify v6

chore: move to aws-amplify v6

---

yarn.lock

fix: update aws-amplify in yarn.lock

---

package.json
yarn.lock

Pin `@mapbox/mapbox-gl-draw` to prevent CJS build issues in NextJS pages router apps using Amplify Geo
Installed tag version in Amplify UI monorepo locally and verified build

fix: pin @mapbox/mapbox-gl-draw to 1.3.0

---

package.json
yarn.lock

Merge #256 from aws-amplify/main
