README.md
package.json
src/AmplifyMapLibreRequest.ts
src/drawClusterLayer.ts
src/drawPoints.ts
yarn.lock

- `createMaplibreMap` uses `Geo.getDefaultMap` to get the map name to pass to maplibre
- `style` parameter now optional if user wants to override which map is loaded
- `drawPoints` uses `Get.getDefaultMap` to get the map style to determine which font set to use
- `style` parameter now optional if user wants to choose which font set to use

chore: update createMaplibreMap and drawPoints to get amplify default map data

---

__tests__/AmplifyMapLibreGeocoder.test.ts
src/AmplifyMapLibreGeocoder.ts
src/index.ts

- Added an AmplifyGeocoder API that wraps `Geo.searchByText` and `Geo.searchByCoordinate` to be used with maplibre-gl-geocoder

feat: added geocoderApi for maplibre-gl-geocoder and amplify

---

package.json
src/amplify-geocoder.css

- Added `amplify-geocoder.css` which sets maplibre-gl-geocoder styles to match the amplify specific style
- Updated build steps for the css file
- This does not update marker styles just yet as that requires some changes to maplibre-gl-geocoder to allow for svg elements (which is what our markers use)

feat: added amplify-geocoder.css to set styles for maplibre-gl-geocoder to match amplify

---

package.json
yarn.lock

- Update `@aws-amplify/core` and `@aws-amplify/geo` to use `geo` tagged versions

fix: update amplify packages to use geo tagged version

---

src/AmplifyMapLibreRequest.ts

Because only some options were passed to Maplibre's map, bearing, pitch, hash, etc. were not working properly.
I responded by passing all properties except region.
transformRequest is passed as is because it will be overwritten later.
After making the changes, I generated the map in another project and confirmed that it actually works.

Fixed some options in Maplibre not working.

---

package.json
rollup.config.js

- Moved bundle name to `AmplifyMapLibre`
- Moved various rollup cli settings to config file

chore: rename bundle to AmplifyMapLibre and move rollup settings to config file

---

src/drawUnclusteredLayer.ts

This allows a user to use their own html popup rather than the default {title, address} format.
Unclustered Layer has an option to render your own popup, however does not implement this feature.
Tested on test enviorment, works fine.

Allow popupRender to work properly

---

.circleci/config.yml

- Pulls amplify-js-samples-staging package and runs e2e tests contained there
- Links maplibre-gl-js-amplify to amplify-js-samples-staging

Add CircleCI Configuration for Pulling Amplify Samples Integ Tests

---

src/drawUnclusteredLayer.ts

- When clicking a point then clicking anywhere away from the point the point was remaining in the highlighted state
- Fixed so when clicking on the map, closing a popup, or any other point it will deselect the original point

Fix: Deselecting Point by Clicking outside map

---

__tests__/drawGeofences.test.ts
src/drawGeofences.ts
src/index.ts
src/types.ts
src/utils.ts

- Added `drawGeofences` function similar to `drawPoints`
- Can pass raw coordinates or `Geofence` objects to render geofences on a map with default styling
- Will add style customizations in a subsequent PR
- Added unit tests

feat: Added drawGeofences

---

__tests__/AmplifyGeofenceControl.test.ts
package.json
src/AmplifyGeofenceControl/AmplifyMapboxDraw.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/geofenceUtils.ts
yarn.lock

- Refactored mapbox draw to it's own class wrapper called AmplifyMapboxDraw
- Updated circle_mode button to draw a circle with radius 1/8 the diagonal length of the screen

feat: add circle mode, refact mapbox draw into own file

---

.github/workflows/publish.yml

fix: change publish workflow if statement

---

src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/public/amplify-ctrl-geofence.css

- Due to css included with amplify-ui the ordering of css imports will affect classes that container the word `amplify` https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/theme/css/styles.scss#L16
- After speaking with Scott seems like this was added intentionally to overly generic styling messing with `amplify` specific styling and it was assumed by the UI team that only Amplify UI would use `amplify` in class names
- Removing it on the UI side will require a lot of work (regression testing) on UI so for now we will just rename our class names
- For future proofing we can also document/recommend customers import Amplify UI css before other Amplify styles we write get loaded
- This will also allow us to use Amplify UI CSS variables in the future

Update class names to be prefixed with geofence

---

API.md
__tests__/drawPoints.test.ts
src/drawPoints.ts

- Update drawPoints to automatically fit the map bounds to include points draw onto the map
- If points are already fit into the current bounds no changes will be made
- Defaults to true
- [] Tests are [changed or added]

feat: add autoFit option to drawPoints

---

package.json

chore: prep geo release v1.2.9

---

__tests__/AmplifyMapLibreGeocoder.test.ts
src/AmplifyMapLibreGeocoder.ts

- Amplify Geo/ Location Service would throw an error when passing in both a bounding box and a proximity parameter, fixed that by prioritizing bbox over proximity params

fix: fix search/getSuggestions when passing in both proximity and bbox

---

__tests__/drawPoints.test.ts
src/drawPoints.ts

- Updates the sourceId used for `drawPoints` to be the same as the `sourceName` passed in as a parameter

fix: update sourceId to be the sourceName passed into drawPoints

---

.circleci/config.yml
.github/workflows/coverage.yml
.github/workflows/publish.yml
.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

- Added semantic-release to use as release process
- Pushes to `main` will release to an unstable npm tag
- Pushes to `release` will publish to the latest npm tag
- Pushes to `geo` will release to `geo` npm tag
- Added `husky` and `commitlint` for commit messaging linting
Example of attempting to do a `bad` commit:
```
❯ git commit --allow-empty -m "foo"
yarn run v1.22.11
$ /Users/thadtrin/workspace/maplibre-gl-js-amplify/node_modules/.bin/commitlint --edit .git/COMMIT_EDITMSG
⧗   input: foo
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for …
```

chore: Switch release process to use semantic-release

---

.github/workflows/publish.yml

- Added gh_token as an environment variable per - https://docs.github.com/en/actions/security-guides/automatic-token-authentication

fix: add github token to publish workflow

---

__tests__/AmplifyGeofenceControl.test.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
yarn.lock

- Separated `createGeofence` and `saveGeofence` behavior because `saveGeofence` with empty string is used for editing behavior while creating geofence with empty string causes a validation error
- Error introduced in - https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/136/files

fix: fix saveGeofence error with empty string

---

__tests__/AmplifyGeofenceControl.test.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts
src/geofenceUtils.ts

- Fixed `isExistingGeofenceId` logic which was actually checking for the inverse
- Added `resetGeofence` logic to its original polygon if it is resetting an existing geofence, otherwise it will reset it to a default polygon

fix: fix isExistingGeofenceId logic, add resetGeofence logic to its original polygon

---

__tests__/AmplifyGeofenceControl.test.ts
src/AmplifyGeofenceControl/index.ts
src/AmplifyGeofenceControl/ui.ts

- When displaying geofences try to fit them into the current map view
- When displaying single geofences just try to update the current map bounds to include those coordinates
- When displaying all geofences update map bounds to include all geofences and then add some padding to the zoom

chore: Add fit zoom on geofence display

---

yarn.lock

Delete and regenerate `yarn.lock` to update minimist to version 1.2.6 in `yarn.lock` in order to fix prototype pollution reported by dependabot: https://github.com/aws-amplify/maplibre-gl-js-amplify/security/dependabot/9

fix: update minimist in yarn.lock

---

package.json
yarn.lock

- Adding empty fs/path packages to fix the mapbox-gl-draw-circle CRA5 polyfill issue
- Working on a fork of mapbox-gl-draw to maplibre-gl-draw which will fix this long term
- Will add e2e tests that test fs/path packages to integ tests in a separate PR

fix: install empty fs/path packages to fix CRA5 polyfill issue

---

__tests__/drawGeofences.test.ts
src/AmplifyGeofenceControl/index.ts
src/drawGeofences.ts

- The newer versions of CRA and CNA when run in dev mode / strict mode do two renders at the start to test the idempotency of renders, this discovered an issue when using the geofence control. When rendering the geofence control multiple times it attempts to draw the geofences in a layer with the same name multiple times coming up with a warning
- Warning pictured below
- Fixed the error by checking first if the geofence layer has been drawn already and returning if so
- Updated drawGeofences to use the same sourceName as passed in

fix: Fix multiple render warning

---

package.json
yarn.lock

- Upgraded maplibre-gl-geocoder to v1.4.0
- Fixed npm resolutions by adding `overrides` field
- Fixed jest type issue with npm install

chore: Update maplibre-geocoder to 1.4.0, fix npm resolutions

---

__tests__/AmplifyMapLibreGeocoder.test.ts
package.json
src/AmplifyMapLibreGeocoder.ts
yarn.lock

Add getSuggestions and searchByPlaceId APIs with unit tests
Manual testing with test data on UI component and unit tests.

feat: autosuggest place id support

---

__tests__/AmplifyMapLibreRequest.test.ts
__tests__/createMap.test.dom.ts
src/AmplifyMapLibreRequest.ts

- Updated to use `Credentials` instead of `Amplify.auth`
- Required as aws amplify is removing the usage of the singleton Amplify usage to get rid of `sideEffects` in their next release

fix: update redentials to be grabbed from Credentials instead of Auth

---

package.json
yarn.lock

Use json5 version later than 2.2.2 to fix vulnerability
https://github.com/aws-amplify/maplibre-gl-js-amplify/security/dependabot/16
- [ x] PR description included
- [ x] `yarn test` passes

chore: use json5 version later than 2.2.2 to fix vulnerability

---

__tests__/AmplifyMapLibreRequest.test.ts
src/AmplifyMapLibreRequest.ts

- When user refreshes credentials and receives an error (often can occur if signing out and not having guest access) the credentials object will be set to some error value without an expiration date. This was causing set timeout to be called instantly as we were not passing a number
- https://github.com/aws-amplify/amplify-ui/issues/3367
- Added a check to ensure that expiration is a number that exists 
- Still needs unit and integration tests

fix: fix infinite refresh occuring when app does not allow guest access

---

package.json
yarn.lock

Latest `aws-amplify` contains security fix that bumps `fast-xml-parser`.
https://github.com/aws-amplify/amplify-ui/security/dependabot/89
```
$ yarn why fast-xml-parser
=> Found "fast-xml-parser@4.2.4"
info Reasons this module exists
- "@aws-amplify#geo#@aws-sdk#client-location#@aws-sdk#client-sts" depends on it
- Hoisted from "@aws-amplify#geo#@aws-sdk#client-location#@aws-sdk#client-sts#fast-xml-parser"
info Disk size without dependencies: "160KB"
info Disk size with unique dependencies: "196KB"
info Disk size with transitive dependencies: "196KB"
info Number of shared dependencies: 1
```

deps: bump lockfile

---

yarn.lock

fix https://github.com/aws-amplify/maplibre-gl-js-amplify/security/dependabot/34

fix: fix vulnerability issue in ip

---

package.json
yarn.lock

Add resolution for fast-xml-parser@4.4.1
Fixes https://github.com/aws-amplify/maplibre-gl-js-amplify/security/dependabot/37

chore(dependabot): add resolution for fast-xml-parser

---

yarn.lock

https://github.com/aws-amplify/maplibre-gl-js-amplify/security/dependabot/38

fix(security): update micromatch dep
